include:
  - '/nso_cicd/pipeline_utils/environments.yml'

# Define the stages of the pipeline
stages:
  - build
  - test
  - deliver
  - deploy_prod

runner pre-reqs:
  stage: .pre
  when: on_success
  script:
    - apt update && apt install sshpass -y

# Step to compile the package in the development NSO environment
package-compilation-🔨:
  stage: build
  when: on_success
  except:
    - main
  script:
    - echo "(Build 🔨) Loading and compiling packages in the NSO dev container"
    # Copy the package to the NSO development environment
    - sshpass -p "$NSO_DEV_PWD" scp -o StrictHostKeyChecking=no -r nso_cicd/packages/$PACKAGE $NSO_DEV_USER@$NSO_DEV_IP:/home/developer/$PACKAGE
    # SSH into the NSO development environment and compile the package
    - sshpass -p "$NSO_DEV_PWD" ssh -o StrictHostKeyChecking=no $NSO_DEV_USER@$NSO_DEV_IP "
          cd /home/developer/ &&
          cp -r $PACKAGE /nso/run/packages &&
          source /opt/ncs/ncs-6.2.5/ncsrc &&
          cd /nso/run/packages/$PACKAGE/src &&
          make clean &&
          make"

# Step to load the compiled package into the testing NSO environment
package-load-📥:
  stage: build
  when: on_success
  except:
    - main
  script:
    - echo "(Build 📥) Loading compiled packages to testing env NSO"
    # SSH into the NSO development environment and reload the package
    - sshpass -p "$NSO_DEV_PWD" ssh -o StrictHostKeyChecking=no $NSO_DEV_USER@$NSO_DEV_IP "
      source /opt/ncs/ncs-6.2.5/ncsrc && 
      echo 'packages reload' | ncs_cli -Cu admin"

# Step to test the loopback service in the NSO testing environment
test-loopback-service-🕵🏽:
  stage: test
  when: on_success
  except:
    - main
  script:
    - echo "(Test 🕵🏽) Deploying service in the NSO test env"
    # Test the service on an IOS-XR device
    - echo "Test IOS-XR"
    - cd nso_cicd/tests/loopback-test && python3 loopback-test.py --nso_url "http://$NSO_DEV_IP:8080" --device "dev-core-rtr01" --username $NSO_DEV_USER --password $NSO_DEV_PWD
    # Test the service on an IOS device
    - echo "Test IOS"
    - python3 loopback-test.py --nso_url "http://$NSO_DEV_IP:8080" --device "dev-dist-rtr01" --username $NSO_DEV_USER --password $NSO_DEV_PWD

# Step to generate and publish the release package
release-publishing-📦:
  stage: deliver
  when: on_success
  except:
    - main
  script:
  - echo "(Deliver 📦) Generating zip" && 
   rm -rf package-artifact/$PACKAGE && 
   mkdir -p package-artifact
  # Copy the package from the NSO development environment to the local directory and create a tarball
  - sshpass -p "$NSO_DEV_PWD" scp -o StrictHostKeyChecking=no -r $NSO_DEV_USER@$NSO_DEV_IP:/nso/run/packages/$PACKAGE $PWD/package-artifact/$PACKAGE/ &&
    cd package-artifact/ && touch nso-package_$PACKAGE_$CI_COMMIT_REF_NAME.tar.gz && ls &&
    tar -czvf nso-package_$PACKAGE_$CI_COMMIT_REF_NAME.tar.gz . 

apply_service-📦:
  stage: deliver
  when: on_success
  script:
    - echo "Apply IOS"
    - python3 nso_cicd/tests/loopback-test/apply.py --nso_url "http://$NSO_DEV_IP:8080" --device "dev-dist-rtr01" --username $NSO_DEV_USER --password $NSO_DEV_PWD

  artifacts:
    when: on_success
    paths:
     - $CI_PROJECT_DIR/package-artifact/nso-package_$PACKAGE_$CI_COMMIT_REF_NAME.tar.gz

# Step to clean up the development environment
cleanup-🗑️:
  stage: .post
  when: always
  allow_failure: true
  script:
    - echo "(Cleanup 🗑️) Removing files from NSO Dev"
    # SSH into the NSO development environment and remove the package files
    - sshpass -p "$NSO_DEV_PWD" ssh -o StrictHostKeyChecking=no $NSO_DEV_USER@$NSO_DEV_IP "
      rm -rf $PACKAGE &&
      rm -rf cd /nso/run/packages/$PACKAGE &&
      source /opt/ncs/ncs-6.2.5/ncsrc && echo 'packages reload force' | ncs_cli -Cu admin"


# Step to deploy the package to the production NSO environment
deploy-production-📬:
  stage: deploy_prod
  when: on_success
  only:
    - main
  script:
    - echo "(Deploy📬) Deployment in production."
    - cd package-artifact/ && ls
    # Copy the package tarball to the NSO production environment
    - sshpass -p "$NSO_PROD_PWD" scp -o StrictHostKeyChecking=no -r nso-package_$PACKAGE_$CI_COMMIT_REF_NAME.tar.gz $NSO_PROD_USER@$NSO_PROD_IP:/home/developer/nso-package_$PACKAGE_$CI_COMMIT_REF_NAME.tar.gz
    # SSH into the NSO production environment, extract the tarball, and reload the package
    - sshpass -p "$NSO_PROD_PWD" ssh -o StrictHostKeyChecking=no $NSO_PROD_USER@$NSO_PROD_IP "
        cd /home/developer/ &&
        tar -xvf nso-package_$PACKAGE_$CI_COMMIT_REF_NAME.tar.gz &&
        rm -rf *.tar.gz &&
        cp -r $PACKAGE /nso/run/packages/loopback &&
        source /opt/ncs/ncs-6.2.5/ncsrc &&    
        cd /nso/run/packages/$PACKAGE/src &&      
        make clean &&
        make &&
        echo 'packages reload' | ncs_cli -Cu admin"